# These overrides are appropriate defaults for deploying this chart on OpenShift

global:
  openshift: true

injector:
  image:
    repository: "registry.connect.redhat.com/hashicorp/vault-k8s"
    tag: "0.14.0-ubi"

  agentImage:
    repository: "registry.connect.redhat.com/hashicorp/vault"
    tag: "1.8.4-ubi"

server:
  image:
    repository: "registry.connect.redhat.com/hashicorp/vault"
    tag: "1.8.4-ubi"
