version: 2
jobs:
  bats-unit-test:
    docker:
        # This image is built from test/docker/Test.dockerfile
        - image: hashicorpdev/vault-helm-test:0.1.0
    steps:
      - checkout
      - run: bats ./test/unit -t
  acceptance:
    docker:
        # This image is build from test/docker/Test.dockerfile
        - image: hashicorpdev/vault-helm-test:0.1.0

    steps:
        - checkout
        - run:
            name: terraform init & apply
            command: |
                echo -e "${GOOGLE_APP_CREDS}" | base64 -d > vault-helm-test.json
                export GOOGLE_CREDENTIALS=vault-helm-test.json
                make provision-cluster
        - run:
            name: Run acceptance tests
            command: bats ./test/acceptance -t

        - run:
            name: terraform destroy
            command: |
                export GOOGLE_CREDENTIALS=vault-helm-test.json
                make destroy-cluster
            when: always
  update-helm-charts-index:
    docker:
      - image: circleci/golang:latest
    steps:
      - run:
          name: update helm-charts index
          command: |
            curl --show-error --silent --fail --user "${CIRCLE_TOKEN}:" \
                -X POST \
                -H 'Content-Type: application/json' \
                -H 'Accept: application/json' \
                -d "{\"branch\": \"master\",\"parameters\":{\"SOURCE_REPO\": \"${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}\",\"SOURCE_TAG\": \"${CIRCLE_TAG}\"}}" \
                "${CIRCLE_ENDPOINT}/${CIRCLE_PROJECT}/pipeline"
workflows:
  version: 2
  build_and_test:
    jobs:
      - bats-unit-test
      - acceptance:
            requires:
                - bats-unit-test
            filters:
                branches:
                    only: master
  update-helm-charts-index:
    jobs:
      - update-helm-charts-index:
          context: helm-charts-trigger-vault
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
